name: Test Action
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize]

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a simple echo
        run: echo "The system is working!"
