'use server'

import { db } from '../db/client'
import { memories } from '../db/schema'
import { eq, sql } from 'drizzle-orm'
import { getServerSession } from '../session/get-server-session'
import { generateText, embed } from 'ai'
import { createOpenAI } from '@ai-sdk/openai'
import { runWithKeyRotation, AllKeysExhaustedError, type SelectedApiKey } from '@/lib/ai/key-manager'
import { getModelClient, toGatewayModelId } from '@/lib/ai/models'

/**
 * Enhances a user prompt using relevant memories and language-model guidance
 * while preserving its original goal.
 *
 * @param rawPrompt - The prompt to enhance
 * @returns The enhanced prompt with leading and trailing whitespace removed
 * @throws If the current session does not contain a user ID
 */
export async function optimizePrompt(rawPrompt: string): Promise<string> {
  const session = await getServerSession()
  if (!session?.user?.id) {
    throw new Error('Unauthorized')
  }

  return runWithKeyRotation('prompt-optimizer', async (selected) => {
    const enriched = await enrichPromptWithMemories(rawPrompt, selected, session.user.id)
    return enhanceWithModel(rawPrompt, enriched, selected)
  })
}

async function enrichPromptWithMemories(rawPrompt: string, selected: SelectedApiKey, userId: string): Promise<string> {
  // Embeddings can only be generated by an OpenAI-compatible endpoint with
  // an embedding model. We keep this fallback simple: if the current key
  // cannot produce embeddings, we just skip the similarity search.
  const hasEmbedding = !selected.provider.startsWith('aigateway') || Boolean(process.env.OPENAI_API_KEY)
  if (!hasEmbedding) return ''

  try {
    const embedder = createOpenAI({
      apiKey: selected.provider === 'openai' ? selected.rawValue : process.env.OPENAI_API_KEY,
    })

    const { embedding } = await embed({
      model: embedder.embedding('text-embedding-3-small') as any,
      value: rawPrompt,
    })

    const embeddingString = `[${embedding.join(',')}]`
    const similarMemories = await db
      .select({ content: memories.content })
      .from(memories)
      .where(eq(memories.userId, userId))
      .orderBy(sql`${memories.embedding} <=> ${embeddingString}::vector`)
      .limit(5)
    return similarMemories.map((m) => m.content).join('\n\n')
  } catch {
    return ''
  }
}

async function enhanceWithModel(rawPrompt: string, contextString: string, selected: SelectedApiKey): Promise<string> {
  const systemPrompt = `You are an expert software engineering assistant.
Your goal is to optimize a user's prompt by incorporating relevant context from their past interactions and memories.
Use the provided semantic context to clarify the user's intent, add useful constraints, and make the prompt more precise.
If the context is irrelevant to the current prompt, you can ignore it or use it lightly.
Do not change the fundamental goal of the user's prompt, just improve its clarity and depth.
Output ONLY the enhanced prompt.`

  const userPrompt = `Original Prompt:\n${rawPrompt}\n\nRelevant Context from Past Memories:\n${contextString ? contextString : 'No relevant past memories found.'}\n\nPlease provide the enhanced prompt:`

  const model = pickPromptOptimizerModel(selected)

  const { text: enhancedPrompt } = await generateText({
    model,
    system: systemPrompt,
    prompt: userPrompt,
  })

  return enhancedPrompt.trim()
}

function pickPromptOptimizerModel(selected: SelectedApiKey): any {
  const modelId = selected.provider === 'aigateway' ? toGatewayModelId('openai', 'gpt-4o') : 'gpt-4o'

  if (selected.provider === 'openai' || selected.provider === 'aigateway') {
    const openai = createOpenAI({
      apiKey: selected.rawValue,
      ...(selected.provider === 'aigateway'
        ? { baseURL: process.env.AI_GATEWAY_BASE_URL || 'https://ai-gateway.vercel.sh/v1' }
        : {}),
    })
    return openai(modelId) as any
  }

  // Fall through to the shared model client so other providers keep working.
  return getModelClient(modelId)
}

// Re-export so callers (including legacy server actions) keep their symbol
// shape if they ever imported differently.
export { AllKeysExhaustedError }
